name: 📊 新規スライド作成
description: Marpを使用して新しいプレゼンテーションスライドを作成します
title: "[Slide] "
labels: ["slide-request", "automation"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 新しいスライドを作成します
        
        このフォームを記入すると、GitHub Actionsが自動的に以下を実行します：
        1. スライドディレクトリを作成（`slides/yyyy-MM-dd-title/`形式）
        2. Markdownスライドファイルを生成
        3. Pull Requestを作成
        4. HTML/PDFを自動生成

  - type: input
    id: title
    attributes:
      label: 📝 プレゼンタイトル（英数字とハイフンのみ）
      description: |
        ディレクトリ名に使用されます。
        例: my-awesome-presentation, introduction-to-marp
      placeholder: "my-presentation"
    validations:
      required: true

  - type: input
    id: title_ja
    attributes:
      label: 📋 プレゼンタイトル（日本語）
      description: スライドの実際のタイトルとして表示されます
      placeholder: "私のプレゼンテーション"
    validations:
      required: true

  - type: dropdown
    id: theme
    attributes:
      label: 🎨 テーマ
      description: プレゼンテーションのスタイルを選択してください
      options:
        - default
        - ビジネス
        - 技術系LT
        - 社内の発表
      default: 0
    validations:
      required: true

  - type: dropdown
    id: duration
    attributes:
      label: ⏱️ 発表時間
      description: |
        時間に応じたテンプレートが適用されます
        - 5分: 8-10枚（LT向け）
        - 10分: 15-20枚（ショートトーク）
        - 30分: 40-50枚（通常セッション）
      options:
        - "5"
        - "10"
        - "30"
      default: 1
    validations:
      required: true

  - type: input
    id: presenter
    attributes:
      label: 👤 発表者名
      description: スライドに表示される発表者の名前
      placeholder: "山田太郎"
    validations:
      required: true

  - type: input
    id: organization
    attributes:
      label: 🏢 所属組織（任意）
      description: 発表者の所属組織や肩書き
      placeholder: "株式会社Example / エンジニア"
    validations:
      required: false

  - type: input
    id: date
    attributes:
      label: 📅 発表日（任意）
      description: プレゼンテーションの予定日（YYYY-MM-DD形式）
      placeholder: "2024-12-25"
    validations:
      required: false

  - type: textarea
    id: content
    attributes:
      label: 📝 スライド内容
      description: |
        Claude/ChatGPTで生成したMarkdown形式のスライド内容を貼り付けてください。
        
        **AIへの推奨プロンプト例：**
        ```
        以下のガイドラインに従って、[時間]分のプレゼンテーションスライドをMarp形式のMarkdownで作成してください。
        
        テーマ: [選択したテーマ]
        タイトル: [プレゼンタイトル]
        対象者: [想定する聴衆]
        
        要件:
        - 1スライドあたり最大400文字、12行まで
        - 各スライドにスピーカーノートを含める
        - --- でスライドを区切る
        
        内容: [話したい内容の概要]
        ```
      placeholder: |
        ---
        # タイトル
        
        サブタイトル
        
        発表者: 名前
        日付: 2024-12-01
        
        ---
        
        # アジェンダ
        
        1. 項目1
        2. 項目2
        3. 項目3
        
        <!-- 
        スピーカーノート:
        - ポイント1
        - ポイント2
        -->
        
        ---
        
        # 内容...
      render: markdown
    validations:
      required: true

  - type: textarea
    id: resources
    attributes:
      label: 🔗 参考リソース（任意）
      description: 参考URL、論文、書籍などのリソース
      placeholder: |
        - https://example.com/reference
        - 書籍: タイトル（著者名）
        - 論文: タイトル（年）
    validations:
      required: false

  - type: checkboxes
    id: options
    attributes:
      label: ⚙️ オプション
      description: 追加の設定オプション
      options:
        - label: ページ番号を表示する
          required: false
        - label: プログレスバーを表示する
          required: false
        - label: ヘッダー/フッターを追加する
          required: false
        - label: HTMLにスピーカーノートを含める
          required: false